# Mengaktifkan Dukungan AndroidX (Wajib untuk dependensi modern)
android.useAndroidX=true
android.enableJetifier=true

# Pengaturan Memori & Encoding
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official

# Mematikan cache agar tidak bentrok di GitHub Runner
org.gradle.caching=false
org.gradle.configuration-cache=false

# Pengaturan Tambahan
android.nonTransitiveRClass=true
org.gradle.workers.max=4
kotlin.compiler.execution.strategy=in-process
googleServices.missing.passthrough=true
