name: Auto Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Step 1: Regenerate folder Android
      - name: Re-generate Android Project
        run: |
          rm -rf android
          flutter create . --platforms=android --org=com.esp32.dashboard

      # Step 2: Matikan pembatasan AGP 9 agar kompatibel dengan library usb_serial
      - name: Fix Gradle AGP Compatibility
        run: |
          echo "android.experimental.artifactory.auto=false" >> android/gradle.properties
          echo "android.suppressUnsupportedCompileSdk=8,9,10,34,35" >> android/gradle.properties
          echo "android.defaults.buildfeatures.buildconfig=true" >> android/gradle.properties

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dashboard-ESP32-APK
          path: build/app/outputs/flutter-apk/app-release.apk
